### ISSUE TITLE
Meta issue: RFC-Clients

### ISSUE THREAD

**Issue by showierdata9978** [meower-media-co/Meower.js#60]
Meower.js needs to follow these RFC goals for it. These will be updated as they are put in.

# Design requirements
- [ ] Cache
	- [X] Users
	- [ ] Posts
	- [ ] Chats
- [x] Use autoget

# Features

- [ ] Post/user reporting.
- [ ] Chats:
    - [ ] Chat Member management 
    - [ ] Creating Chats
- [x] Logging in
- [ ] Signing up
- [ ] settings
- [ ] Searching
- [ ]Blocking/reporting users
- [x] Bridge support
- [ ]Sending typing indication. You do not need to show who is typing.
- [x] Option to switch to an external sever.
